### ISSUE TITLE
[CRASH] "Detuning locks due to high load per core" and "Unknown btype in replyToBlockedClientTimedOut()" causes Master Pod restart every hour

### ISSUE THREAD

**Issue by setevoy2** [Snapchat/KeyDB#586]
**Crash report**

Error log:

```
2023-03-02 17:02:12 | {"log":"  Suspect RAM error? Use keydb-server --test-memory to verify it.\n","stream":"stdout","time":"2023-03-02T15:02:12.334358807Z"}
-- | --
  |   | 2023-03-02 17:02:12 | {"log":"\n","stream":"stdout","time":"2023-03-02T15:02:12.334356344Z"}
  |   | 2023-03-02 17:02:12 | {"log":"           https://github.com/JohnSully/KeyDB/issues\n","stream":"stdout","time":"2023-03-02T15:02:12.334353566Z"}
  |   | 2023-03-02 17:02:12 | {"log":"\n","stream":"stdout","time":"2023-03-02T15:02:12.334350996Z"}
  |   | 2023-03-02 17:02:12 | {"log":"       Please report the crash by opening an issue on github:\n","stream":"stdout","time":"2023-03-02T15:02:12.33434766Z"}
  |   | 2023-03-02 17:02:12 | {"log":"\n","stream":"stdout","time":"2023-03-02T15:02:12.334330635Z"}
  |   | 2023-03-02 17:02:12 | {"log":"=== KEYDB BUG REPORT END. Make sure to include from START to END. ===\n","stream":"stdout","time":"2023-03-02T15:02:12.334327754Z"}
  |   | 2023-03-02 17:02:12 | {"log":"\n","stream":"stdout","time":"2023-03-02T15:02:12.334325205Z"}
  |   | 2023-03-02 17:02:12 | {"log":"1:19:S 02 Mar 2023 15:02:12.334 # Guru Meditation: Unknown btype in replyToBlockedClientTimedOut(). #blocked.cpp:246\n","stream":"stdout","time":"2023-03-02T15:02:12.334322359Z"}
  |   | 2023-03-02 17:02:12 | {"log":"1:19:S 02 Mar 2023 15:02:12.334 # !!! Software Failure. Press left mouse button to continue\n","stream":"stdout","time":"2023-03-02T15:02:12.334319743Z"}
  |   | 2023-03-02 17:02:12 | {"log":"1:19:S 02 Mar 2023 15:02:12.334 # ------------------------------------------------\n","stream":"stdout","time":"2023-03-02T15:02:12.334317171Z"}
  |   | 2023-03-02 17:02:12 | {"log":"=== KEYDB BUG REPORT START: Cut \u0026 paste starting from here ===\n","stream":"stdout","time":"2023-03-02T15:02:12.334314166Z"}
  |   | 2023-03-02 17:02:12 | {"log":"\n","stream":"stdout","time":"2023-03-02T15:02:12.334311438Z"}
  |   | 2023-03-02 17:02:12 | {"log":"\n","stream":"stdout","time":"2023-03-02T15:02:12.334309126Z"}
  |   | 2023-03-02 17:02:12 | {"log":"NOTICE: Detuning locks due to high load per core: 101.34%\n","stream":"stdout","time":"2023-03-02T15:02:12.33430637Z"}
  |   | 2023-03-02 17:02:12 | {"log":"NOTICE: Detuning locks due to high load per core: 125.88%\n","stream":"stdout","time":"2023-03-02T15:02:12.334303753Z"}
  |   | 2023-03-02 17:02:12 | {"log":"NOTICE: Detuning locks due to high load per core: 153.54%\n","stream":"stdout","time":"2023-03-02T15:02:12.334300778Z"}
  |   | 2023-03-02 17:02:12 | {"log":"NOTICE: Detuning locks due to high load per core: 114.26%\n","stream":"stdout","time":"2023-03-02T15:02:12.334297792Z"}
  |   | 2023-03-02 17:02:12 | {"log":"NOTICE: Detuning locks due to high load per core: 99.02%\n","stream":"stdout","time":"2023-03-02T15:02:12.334294906Z"}
```

**Aditional information**

1. Amazon Linux
2. Amazon EKS
3. KeyDB installed from the [KeyDB Helm chart](https://artifacthub.io/packages/helm/enapter/keydb ) using AppVersion `6.3.2` (latest)

Steps to reproduce:
1. Deploy KeyDB cluster
2. every hour on 00-01 minute, the Master Pod reports about "Detuning locks due to high load per core"
3. then, Master will throw the "Unknown btype in replyToBlockedClientTimedOut()" error
4. then, Master Pod goes to restart

`keydb-server --test-memory 256` does not reports any memory issues.
KubernetesWorker Node have enough resources (CPU/RAM)
KeyDB Pods have enough `resources.requests` and `limits`

**Comment by msotheeswaran** [comment]
Hi @setevoy2 can you provide the full crash log, the configs you are using, and describe the traffic patterns to the server at the time of crash?

**Comment by setevoy2** [comment]
Hi, @msotheeswaran

Actually, logs from the issue description are all I have and all that is relevant to the issue.
Is there any additional logging that can be enabled? I may try to set the `loglevel notice` if this will help.

The configs all are default, here is my `values.yaml` file content used to deploy the chart:

```
keydb:
  nodes: 2
  existingSecret: "gitlab-cluster-keydb-secret"
  configExtraArgs:
    - maxmemory-policy: allkeys-lru
    - maxmemory: "2500mb"
    - save: ""
    - appendonly: "no"
    - crash-log-enabled: "no"
  persistentVolume:
    size: 5Gi
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 64Mi
  nodeSelector:
    pool: gitlab_cluster
  tolerations:
  - key: selector
    operator: "Equal"
    value: gitlab_cluster
    effect: NoSchedule
  serviceMonitor:
    enabled: true
    labels:
      release: kps
  exporter:
    enabled: true
```

Not sure about the "traffic patterns". We are using it for our Gitlab self-hosted cluster. 
I know, it's used by the Sidekiq service which is a component of Gitlab for some caches, and by the Webservice. But no idea (and can't find anything in Gitlab's docs) about how exactly it is used.

Btw, despite the `crash-log-enabled: "no"` option being set, KeyDB creates a lot of `core.*` files:

```root@gitlab-cluster-keydb-1:/data# ls -l core.* | wc -l
404
```
It's been since yesterday.
